version: '3'

services:
  app:
    image: clojure:tools-deps-alpine
    working_dir: "${PWD}"
    command: "true"
    ports:
      - "4444:4444" # nrepl
      - "4445:4445" # http
    environment:
      - "GITLIBS=.gitlibs"
      - "CLJ_CONFIG=${PWD}/docker-clojure"
    volumes:
      - ".:${PWD}:cached"
