version: '3'

services:
  app:
    image: clojure:tools-deps-alpine
    working_dir: "${PWD}"
    command: "true"
    ports:
      - "4444:4444" # nrepl
    environment:
      - "GITLIBS=${PWD}/.gitlibs"
    volumes:
      - ".:${PWD}:cached"
